# Generated by Django 5.1.6 on 2025-02-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filmactor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filmcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': False},
        ),
    ]
