# Generated by Django 5.1.6 on 2025-02-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filmactor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='filmcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
    ]
