# Generated by Django 5.1.6 on 2025-03-09 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_wishlist'),
        ('films', '0003_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('score', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='films.film')),
            ],
            options={
                'db_table': 'film_score',
                'unique_together': {('film', 'customer')},
            },
        ),
    ]
