# Generated by Django 5.1.6 on 2025-02-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_staff_options_alter_store_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
    ]
