# Generated by Django 5.1.6 on 2025-02-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='store_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
