# Generated by Django 5.1.6 on 2025-03-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_user'),
        ('films', '0003_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='films.film')),
                ('last_update', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('film', 'customer')},
            },
        ),
    ]
