# Generated by Django 5.1.6 on 2025-03-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_wishlist'),
        ('films', '0003_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='films.film'),
        ),
    ]
