# Generated by Django 5.1.6 on 2025-02-15 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('films', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='films.inventory')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.staff')),
            ],
            options={
                'db_table': 'rental',
                'unique_together': {('rental_date', 'inventory', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.staff')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.rental')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
