# Generated by Django 5.1.6 on 2025-02-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'managed': False},
        ),
    ]
