# Generated by Django 5.1.6 on 2025-02-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_alter_rental_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={},
        ),
    ]
